<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductVariationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Dữ liệu mẫu cho product_variations
        DB::table('product_variations')->insert([
            [
                "product_id" => 1,
                "sku" => "Geometric-1",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => 0.0,
                "stock_quantity" => 100,
                "deleted_at" => "2025-03-20 15:51:04",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "17-1742485760251-19",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 1000,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "17-1742485760251-20",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 379000,
                "sale_price" => null,
                "stock_quantity" => 1000,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "17-1742485760251-21",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 399000,
                "sale_price" => null,
                "stock_quantity" => 100,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "17-1742485760251-22",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 99,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "18-1742485760251-19",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 99,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "18-1742485760251-20",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 99,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "18-1742485760251-21",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 99,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "product_id" => 1,
                "sku" => "18-1742485760251-22",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 101,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 2,
                "sku" => "25-1742529211148-19",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 379000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 2,
                "sku" => "17-1742529211148-19",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 389000,
                "sale_price" => null,
                "stock_quantity" => 501,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "25-1742529458164-19",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "25-1742529458164-20",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 888,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "25-1742529458164-21",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 888,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "17-1742529458164-19",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 777,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "17-1742529458164-20",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 666,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 3,
                "sku" => "17-1742529458164-21",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 319000,
                "sale_price" => null,
                "stock_quantity" => 555,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 4,
                "sku" => "17-1742529736548-20",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 349000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 4,
                "sku" => "17-1742529736548-21",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 349000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 4,
                "sku" => "25-1742529736548-20",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 359000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 4,
                "sku" => "25-1742529736548-21",
                "weight" => 170,
                "variant_image" => null,
                "regular_price" => 359000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 5,
                "sku" => "26-1742530002196-20",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 329000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 5,
                "sku" => "26-1742530002196-21",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 329000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 5,
                "sku" => "25-1742530002196-20",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 339000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 5,
                "sku" => "25-1742530002196-21",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 339000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 6,
                "sku" => "LIFESTYLE",
                "weight" => 190,
                "variant_image" => null,
                "regular_price" => 450000,
                "sale_price" => 350000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 7,
                "sku" => "30-1742634241418-1",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 419000,
                "sale_price" => 389000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 7,
                "sku" => "30-1742634241418-2",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 419000,
                "sale_price" => 389000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 7,
                "sku" => "31-1742634241418-1",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 419000,
                "sale_price" => 399000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 7,
                "sku" => "31-1742634241418-2",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 419000,
                "sale_price" => 409000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 8,
                "sku" => "32-1742634527875-21",
                "weight" => 210,
                "variant_image" => null,
                "regular_price" => 390000,
                "sale_price" => 349000.0,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 9,
                "sku" => "Slim",
                "weight" => 190,
                "variant_image" => null,
                "regular_price" => 450000,
                "sale_price" => 390000.0,
                "stock_quantity" => 500,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 10,
                "sku" => "18-1742636837440-1",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 249000,
                "sale_price" => null,
                "stock_quantity" => 500,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 10,
                "sku" => "18-1742636837440-2",
                "weight" => 200,
                "variant_image" => null,
                "regular_price" => 249000,
                "sale_price" => null,
                "stock_quantity" => 450,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 11,
                "sku" => "QSSLIM",
                "weight" => 100,
                "variant_image" => null,
                "regular_price" => 400000,
                "sale_price" => 350000.0,
                "stock_quantity" => 999,
                "deleted_at" => "2025-03-22 10:04:19",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 11,
                "sku" => "37-1742637806446",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 390000,
                "sale_price" => null,
                "stock_quantity" => 999,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 11,
                "sku" => "17-1742637806446",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 390000,
                "sale_price" => null,
                "stock_quantity" => 888,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [

                "product_id" => 11,
                "sku" => "36-1742637806446",
                "weight" => 150,
                "variant_image" => null,
                "regular_price" => 390000,
                "sale_price" => null,
                "stock_quantity" => 666,
                "deleted_at" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
    /**
     * Hàm tạo mã SKU cho sản phẩm dựa trên product_id.
     *
     * @param int $productId
     * @return string
     */
}
